<?
define("TBL_ADMIN_USER","tbl_admin_user");
define("TBL_CLIENTS","tbl_clients");
define("TBL_CLIENT_DOCUMENTS","tbl_client_documents");
define("TBL_CLIENT_NOTES","tbl_client_notes");
define("TBL_CLIENT_SERVICES","tbl_client_services");
define("TBL_CLIENT_TO_DO","tbl_client_to_do");
define("TBL_CONSULTANCY","tbl_consultancy");
define("TBL_DISCOUNT","tbl_discount");
define("TBL_EMAIL_TEMPLATE","tbl_email_template");
define("TBL_EMPLOYEE","tbl_employee");
define("TBL_EMPLOYEE_PACKAGE","tbl_employee_package");
define("TBL_EMPLOYEE_ROLE","tbl_employee_role");
define("TBL_FULL_PAYMENT","tbl_full_payment");
define("TBL_INSTALLMENT","tbl_installment");
define("TBL_INTERNAL_DOCUMENTS","tbl_internal_documents");
define("TBL_INTERNAL_NOTES","tbl_internal_notes");
define("TBL_INVOICE","tbl_invoice");
define("TBL_LEADS","tbl_leads");
define("TBL_LOG","tbl_log");
define("TBL_PART_PAYMENT","tbl_part_payment");
define("TBL_PAYMENT","tbl_payment");
define("TBL_PAYMENT_TRANSACTION","tbl_payment_transaction");
define("TBL_PROJECT","tbl_project");
define("TBL_QUESTIONNAIRE","tbl_questionnaire");
define("TBL_QUESTIONS","tbl_questions");
define("TBL_QUESTIONS_LINE_ITEM","tbl_questions_line_item");
define("TBL_REFERENCE","tbl_reference");
define("TBL_SERVICE","tbl_service");
define("TBL_SERVICE_CATEGORIES","tbl_service_categories");
define("TBL_SERVICE_FAQ","tbl_service_faq");
define("TBL_SERVICE_FEATURES","tbl_service_features");
define("TBL_SERVICE_STEPS","tbl_service_steps");
define("TBL_SERVICE_STEPS_LINE_ITEM","tbl_service_steps_line_item");
define("TBL_TEAMS","tbl_teams");
define("TBL_TERMS_AND_CONDTIONS","tbl_terms_and_condtions");
define("TBL_TO_DO","tbl_to_do");
define("TBL_WL_MEMBERS","tbl_wl_members");
define("TBL_WL_MEMBERSHIP","tbl_wl_membership");


// define function code 
define("FUN_EMP","function_emp")
?>